### ISSUE TITLE
Install via flakes failing with book-darwin-manual render error

### ISSUE THREAD

**Issue by taylrfnt** [LnL7/nix-darwin#1176]
Not sure if this is the right forum for this error, but I am trying to get a fresh install of nix-darwin working on my Mac (`aarch64`, macOS 14.6.1 [Sonoma]), and following the instructions in the README for flakes results in the following error:

```
❯ nix run nix-darwin --extra-experimental-features "nix-command flakes" -- switch --flake ~/nix/darwin#base-config -v
building the system configuration...
these 18 derivations will be built:
  /nix/store/139h0bmyzndmzh8ansvhm84ky14gvazq-org.nixos.nix-daemon.plist.drv
  /nix/store/b6ravmpm7qgnh4p4jjf1bbsdbwnhhvjp-set-environment.drv
  /nix/store/j2n1x652hsmdw77idgy8k87ny5kyi65a-etc-bashrc.drv
  /nix/store/m2zmvi3h1k2zqjq1m27j45pks6ig091k-etc-zshenv.drv
  /nix/store/1yvpnv67y7bvifbdws5jmf8qgkarbacp-etc.drv
  /nix/store/xffncjcpj65s2x52szzr3zw9q0dvd098-org.nixos.activate-system.plist.drv
  /nix/store/60ngal26xn468nf3lg23pf1njirgxbdq-launchd.drv
  /nix/store/4bzzx1f0r9qgw48mc47b64i6ab5crq1g-darwin-manual-html.drv
  /nix/store/94fnswpxypzbkbjw0fnlyjhm0qbryp2l-darwin-help.drv
  /nix/store/3fglhp2d6zpwxnqmnnv9v96smvcrnkw5-darwin-manual-html.drv
  /nix/store/bf9w4zgisxpyapj79w5z0igjgrz8mfh6-darwin-help.drv
  /nix/store/fx6ygnv6z8qnhni7xzlipyz6kksymkr3-system-applications.drv
  /nix/store/klhfigx8cwasddklmg12ly55hxrr58k1-system-path.drv
  /nix/store/x1wnprjhx4z6zw0vhis9q571ccz3qcj1-darwin-system-25.05pre-git+darwin5.drv
  /nix/store/c2k55j1rdahi9phsdw4iqn2d2sd356q1-darwin-uninstaller.drv
  /nix/store/cjgc4pgvh5d2xc4vzvzqls1qba16xcwi-system-path.drv
  /nix/store/d2p7xzpabjpcidj1ss7g2bgn8zszklwd-system-applications.drv
  /nix/store/2y6rzy5wgn4mkf7iqsszd0d0r7mmkz2p-darwin-system-25.05.20241116.34a6264+darwin5.2bcef10.drv
building '/nix/store/4bzzx1f0r9qgw48mc47b64i6ab5crq1g-darwin-manual-html.drv'...
error: builder for '/nix/store/4bzzx1f0r9qgw48mc47b64i6ab5crq1g-darwin-manual-html.drv' failed with exit code 1;
       last 25 log lines:
       >
       > Traceback (most recent call last):
       >   File "/nix/store/fwm8446gaxgp0jagm09cmb0zjqgqryml-nixos-render-docs-0.0/lib/python3.12/site-packages/nixos_render_docs/__init__.py", line 49, in main
       >     manual.run_cli(args)
       >   File "/nix/store/fwm8446gaxgp0jagm09cmb0zjqgqryml-nixos-render-docs-0.0/lib/python3.12/site-packages/nixos_render_docs/manual.py", line 725, in run_cli
       >     _run_cli_html(args)
       >   File "/nix/store/fwm8446gaxgp0jagm09cmb0zjqgqryml-nixos-render-docs-0.0/lib/python3.12/site-packages/nixos_render_docs/manual.py", line 717, in _run_cli_html
       >     md.convert(args.infile, args.outfile)
       >   File "/nix/store/fwm8446gaxgp0jagm09cmb0zjqgqryml-nixos-render-docs-0.0/lib/python3.12/site-packages/nixos_render_docs/manual.py", line 532, in convert
       >     super().convert(infile, outfile)
       >   File "/nix/store/fwm8446gaxgp0jagm09cmb0zjqgqryml-nixos-render-docs-0.0/lib/python3.12/site-packages/nixos_render_docs/manual.py", line 42, in convert
       >     raise RuntimeError(f"failed to render manual {infile}") from e
       > RuntimeError: failed to render manual manual.md
       > error:
       >     failed to render manual manual.md
       >
       > caused by:
       >
       > Identifiers present in the source must have a mapping in the redirects file.
       >     - book-darwin-manual
       >
       >     This can happen when an identifier was added or renamed.
       >     Please update doc/redirects.json or nixos/doc/manual/redirects.json!
       >
       > NOTE: If your Manual build passes locally and you see this message in CI, you probably need a rebase.
       For full logs, run 'nix-store -l /nix/store/4bzzx1f0r9qgw48mc47b64i6ab5crq1g-darwin-manual-html.drv'.
error: 1 dependencies of derivation '/nix/store/d2p7xzpabjpcidj1ss7g2bgn8zszklwd-system-applications.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2y6rzy5wgn4mkf7iqsszd0d0r7mmkz2p-darwin-system-25.05.20241116.34a6264+darwin5.2bcef10.drv' failed to build
```

Here's the `flake.nix` I'm supplying, the only differences from the instructions and my setup is the name of the flake (`base`) and file location (`~/nix/darwin`):

```
{
  description = "Example nix-darwin system flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nix-darwin.url = "github:LnL7/nix-darwin";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = inputs@{ self, nix-darwin, nixpkgs }:
  let
    configuration = { pkgs, ... }: {
      # List packages installed in system profile. To search by name, run:
      # $ nix-env -qaP | grep wget
      environment.systemPackages =
        [ pkgs.vim
        ];

      # Necessary for using flakes on this system.
      nix.settings.experimental-features = "nix-command flakes";

      # Enable alternative shell support in nix-darwin.
      # programs.fish.enable = true;

      # Set Git commit hash for darwin-version.
      system.configurationRevision = self.rev or self.dirtyRev or null;

      # Used for backwards compatibility, please read the changelog before changing.
      # $ darwin-rebuild changelog
      system.stateVersion = 5;

      # The platform the configuration will be used on.
      nixpkgs.hostPlatform = "aarch64-darwin";
    };
  in
  {
    # Build darwin flake using:
    # $ darwin-rebuild build --flake .#base
    darwinConfigurations."base" = nix-darwin.lib.darwinSystem {
      modules = [ configuration ];
    };

    # Expose the package set, including overlays, for convenience.
    darwinPackages = self.darwinConfigurations."base".pkgs;
  };
}
```

**Comment by n8henrie** [comment]
Was about to post the same.

`nix build github:LnL7/nix-darwin#manualHTML` works without issues though.

**Comment by teekennedy** [comment]
There's a new redirects system that got introduced yesterday in [this commit](https://github.com/NixOS/nixpkgs/commit/5b8a71496879d819291c6d7d919f90a7e60d60ad) to nixpkgs-unstable.

Running the installer with the commit pinned to the commit before the redirects system was introduced, I was able to install nix-darwin successfully.

I followed the [flake-based instructions in nix-darwin's README](https://github.com/LnL7/nix-darwin?tab=readme-ov-file#step-1-creating-flakenix) to create a flake.nix, then updated the nixpkgs url before installation:

`nixpkgs.url = "github:NixOS/nixpkgs/8809585e6937d0b07fc066792c8c9abf9c3fe5c4";`

**Comment by satwanjyu** [comment]
pinning works, thank you @teekennedy !

**Comment by samuelhnrq** [comment]
Well okay, but is this issue being tracked for real/upstream at `book-darwin-manual`?
Does that package need any changes to be compatible with the "redirects system" thing?
Anywhere we can keep track of the status, so we can remove the pin eventually?

**Comment by al3xtjames** [comment]
This patch fixes the build of the manual (`nix build '.#manualHTML'`):

```patch
diff --git a/doc/manual/default.nix b/doc/manual/default.nix
index deada0a..6fb1775 100644
--- a/doc/manual/default.nix
+++ b/doc/manual/default.nix
@@ -82,6 +82,7 @@ in rec {
       # TODO: --manpage-urls?
       nixos-render-docs -j $NIX_BUILD_CORES manual html \
         --manpage-urls ${pkgs.writeText "manpage-urls.json" "{}"} \
+        --redirects ${./redirects.json} \
         --revision ${lib.escapeShellArg revision} \
         --generator "nixos-render-docs ${lib.version}" \
         --stylesheet style.css \
diff --git a/doc/manual/redirects.json b/doc/manual/redirects.json
new file mode 100644
index 0000000..46e6796
--- /dev/null
+++ b/doc/manual/redirects.json
@@ -0,0 +1,5 @@
+{
+  "book-darwin-manual": [
+    "index.html#book-darwin-manual"
+  ]
+}
```

However, this breaks support for older revisions of nixpkgs.

**Comment by teekennedy** [comment]
@al3xtjames I'm working on the same thing. I was going to make the `--redirects` flag be conditional on the version of nixos-render-docs, but nixos-render-docs has version `0.0`.

At this point I'm trying to find some way for the build to detect whether the nixos-render-docs command supports the flag.
