### ISSUE TITLE
How to pass hombrew build options?

### ISSUE THREAD

**Issue by ashkan-leo** [LnL7/nix-darwin#314]
Hello!
I was trying out the new homebrew functionality. I was wondering how I should pass the installation options of the brew formulae. 

For example how should I write `brew install emacs-plus@28' --with-ctags --with-debug --with-xwidgets --with-native-comp --with-dbus --with-mailutils --with-emacsicon4-icon` in nix?

**Comment by ashkan-leo** [comment]
Adding the following will result an error.
```nix
    extraConfig = ''
      brew "emacs-plus@28", args:["--with-ctags", "--with-debug", "--with-xwidgets", "--with-native-comp", "--with-dbus", "--with-mailutils", "--with-emacsicon4-icon"]
    '';
```

```
setting up user launchd services...
Homebrew bundle...
Using homebrew/cask
Using homebrew/cask-drivers
Using homebrew/cask-fonts
Using homebrew/cask-versions
Using homebrew/core
Using homebrew/services
Using d12frosted/emacs-plus
Warning: '' formula is unreadable: No available formula with the name "".
Error: undefined method `split' for nil:NilClass
Please report this bug:
  https://github.com/Homebrew/homebrew-bundle/issues
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:105:in `formula_in_array?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:121:in `formula_installed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:168:in `installed?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:36:in `install_change_state!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:27:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/brew_installer.rb:12:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:35:in `block in install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/installer.rb:11:in `install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/lib/bundle/commands/install.rb:10:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd/bundle.rb:94:in `bundle'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

```

**Comment by ashkan-leo** [comment]
I'm closing this issue. It would be nice to have the functionality to specify build arguments in `brew = {...}` directly, but it's not a crucial thing.
